#ifndef AC3FILTER_VER
#define AC3FILTER_VER_MAJOR 2
#define AC3FILTER_VER_MINOR 00
#define AC3FILTER_VER_RELEASE "a"
#define AC3FILTER_VER_QUOTE(x) #x
#define AC3FILTER_VER_(major, minor, release) AC3FILTER_VER_QUOTE(major) "." AC3FILTER_VER_QUOTE(minor) release
#define AC3FILTER_VER AC3FILTER_VER_(AC3FILTER_VER_MAJOR, AC3FILTER_VER_MINOR, AC3FILTER_VER_RELEASE)
#endif
